[package]
name = "cpu_temp"
version = "0.1.0"
authors = ["tree <treed018@odu.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "0.2.11"
num = "0.2.1"
num-traits = "0.2.11"
string-builder = "0.2.0"